services:
  website:
    image: ghcr.io/trans-aether-tranquilizer-automata/website:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - BOT_INVITE=invite_here
      - DISCORD_INVITE=super_cool_invite_here
      - SOURCE_URL=https://github.com/Trans-AEther-Tranquilizer-Automata/Website
